### ISSUE TITLE
Weird Boss Bug, World 2_1

### ISSUE THREAD

**Issue by jaentan** [2awesomestudio/DimensionDriveIssueTracker#394] opened 2017-05-31 19:08 UTC
Right before I record this, I removed the turrets right before the boss appears and as soon the boss appears, I have complete the level without destroying the boss. 

Video clip: https://youtu.be/mPplQ0hgcGQ

[output_log.txt](https://github.com/2awesomestudio/DimensionDriveIssueTracker/files/1042568/output_log.txt)

**Comment by hexxellor** [comment] 2017-06-04 10:38
### Description

I tried to duplicate this on Mac OS X and was unable to get the exact same results, however, I did have the same outcome 

When I reached the end of the level I destroyed all but the far right turret (purely because I screwed up) and then the level ended without a boss or sub-boss appearing at all.

### Reproduction Steps
1. Just play to the end of the level
2. Destroy the turrets (not sure if it's required)
3. Level ends.

### Build
Game Version - Build 0.8.1.41
OS - Mac OS Tested.

No errors were shown at any point during this happening.

**Comment by hexxellor** [comment] 2017-07-25 13:02
Verified as fixed in build v0.8.2.1.

**Closed by hexxellor** 2017-07-25 13:02 UTC
Labels: bug, To be verified
